[main]
shell=fish
include=~/.local/state/omarchy/current/theme/foot.ini
term=xterm-256color
font=JetBrainsMono Nerd Font:size=14
pad=14x14
initial-window-mode=windowed
workers=0

[scrollback]
lines=10000
multiplier=7.0

[cursor]
style=block
blink=no

[key-bindings]
#clipboard-copy=Control+Insert Control+Shift+c XF86Copy
#clipboard-paste=Shift+Insert Control+Shift+v XF86Paste
#clipboard-copy=Control+c
clipboard-paste=Control+v
primary-paste=none
search-start=Control+f
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0

[text-bindings]
#\x03=Control+Shift+c
# Send Shift+Return as CSI-u so TUIs can distinguish it from Return.
\x1b[13;2u=Shift+Return
# Send Alt+Shift+Return as CSI-u so tmux can match M-S-Enter.
\x1b[13;4u=Mod1+Shift+Return
