// tty7 agent-hook opencode bridge — generated by tty7, do not edit.
// Bridges OpenCode plugin events onto `tty7 agent-hook opencode <event>`,
// which is inert outside tty7 (gated on the TTY7 env var).
export const Tty7Presence = async ({ $ }) => {
  if (!process.env["TTY7"]) return {}
  const cmd = "\"/tmp/.mount_tty7.aclBGlk/usr/bin/tty7-app\" agent-hook opencode "
  const emit = (event) => $`sh -c ${cmd + event}`.quiet().nothrow()

  // Plugin load = the agent is running in this pane.
  await emit("session-start")

  return {
    dispose: async () => {
      await emit("session-end")
    },
    "tool.execute.before": async () => {
      await emit("prompt-submit")
    },
    "permission.ask": async () => {
      await emit("permission-request")
    },
    event: async ({ event }) => {
      if (event.type === "session.idle") {
        await emit("stop")
      } else if (event.type === "permission.replied") {
        await emit("prompt-submit")
      }
    },
  }
}
