# See https://wiki.hyprland.org/Configuring/Binds/
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

unbind = Super, Super_L
unbind = Super, Super_R
unbind = Super+Shift, S

bindle = Ctrl,F12, exec, qs -c $qsConfig ipc call brightness increment || brightnessctl s 5%+ # [hidden]
bindle = Ctrl,F11, exec, qs -c $qsConfig ipc call brightness decrement || brightnessctl s 5%- # [hidden]
bindle = Ctrl,F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ # [hidden]
bindle = Ctrl,F1, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%- # [hidden]
# bindd = ALT, 4, Lock, exec, hyprlock # Lock

#!
##! Group
bind = Super CTRL, G, togglegroup # Toggle Grouping for active window
bind = ALT, l, changegroupactive, f # Focus next window in group
bind = ALT, h, changegroupactive, b # Focus previous window in group
bind = ALT SHIFT, l, movegroupwindow, f # Swap with next window in group
bind = ALT SHIFT, h, movegroupwindow, b # Swap with previous window in group

bind = Super CTRL, H, movewindoworgroup, l # Move window in/out of group in/to left
bind = Super CTRL, L, movewindoworgroup, r # Move window in/out of group in/to right
bind = Super CTRL, K, movewindoworgroup, u # Move window in/out of group in/to up
bind = Super CTRL, J, movewindoworgroup, d # Move window in/out of group in/to down
##! Misc
bind = Super, Escape, workspace, previous
unbind = Super, Space
bind = Super, Space, exec, hyprctl switchxkblayout kanata next

bind= Super, R, global, caelestia:launcher

unbind = Super+Shift, S
##! Session
bind = Super+Shift, S, movetoworkspace, special
binde = CTRL+SHIFT, left, resizeactive,-15 0
binde = CTRL+SHIFT, right, resizeactive,15 0
binde = CTRL+SHIFT, up, resizeactive,0 -15
binde = CTRL+SHIFT, down, resizeactive,0 15
binde = CTRL+SHIFT, l, resizeactive, 15 0
binde = CTRL+SHIFT, h, resizeactive,-15 0
binde = CTRL+SHIFT, k, resizeactive, 0 -15
binde = CTRL+SHIFT, j, resizeactive, 0 15

unbind = Super, H
unbind = Super, L
unbind = Super, J
unbind = Super, K
bind = Super, H, movefocus, l # [hidden]
bind = Super, L, movefocus, r # [hidden]
bind = Super, K, movefocus, u # [hidden]
bind = Super, J, movefocus, d # [hidden]
unbind = Super+Shift, H
unbind = Super+Shift, L
unbind = Super+Shift, J
unbind = Super+Shift, K
bind = Super+Shift, H, movewindow, l # [hidden]
bind = Super+Shift, L, movewindow, r # [hidden]
bind = Super+Shift, K, movewindow, u # [hidden]
bind = Super+Shift, J, movewindow, d # [hidden]

##! Apps
bind = Super, Z, exec, zed # Zed editor
